### ISSUE TITLE
训练代码

### ISSUE THREAD

**Issue by Frank-Zhou-01** [Riponcs/Turb-Seg-Res#1]
你好，可以提供一下训练的代码吗

**Comment by SWALLOWhajnal** [comment]
Found a bug where the processed video frames will have gray bars on the edges when clipping. Is this because no clipped pixel backfill is done?

**Comment by Riponcs** [comment]
> 你好，可以提供一下训练的代码吗
To train the Restormer model, you can use this code:[Restormer Implementation](https://github.com/leftthomas/Restormer), and for Dataset Generation use the [Turbulence Simulator Code](https://github.com/Riponcs/QuickTurbSim) on [MIT Place Dataset](https://www.kaggle.com/datasets/nickj26/places2-mit-dataset).

**Comment by Riponcs** [comment]
> Found a bug where the processed video frames will have gray bars on the edges when clipping. Is this because no clipped pixel backfill is done?

Yes, for simplicity during stabilization approach, I didn't use pixel backfill from other frames resulting in  gray bars on the edge.

**Comment by Tara-Liu** [comment]
Hello, what dataset did you use to train Restatemer?

**Comment by Tara-Liu** [comment]
Hello, what dataset did you use to train the Restaormer?

**Comment by Riponcs** [comment]
I have used a Turbulence Simulated MIT Place Dataset to train Restormer. The simulation was done using: [QuickTurbSim](https://github.com/Riponcs/QuickTurbSim).
